### ISSUE TITLE
Babel config should default to .babelrc, but fall back to package.json in current directory

### ISSUE THREAD

**Issue by austinkelleher** [lasso-js/lasso-babel-transform#3]
lasso-babel-transform currently looks for the `babel` property in the root package.json. If it exists, it sets the babel configuration to that. I don't believe that is the correct behavior.

From the [Babel documentation](https://babeljs.io/docs/usage/babelrc/):

> "Babel will look for a .babelrc in the current directory of the file being transpiled. If one does not exist, it will travel up the directory tree until it finds either a .babelrc, or a package.json with a "babel": {} hash within."

**Comment by patrick-steele-idem** [comment]
The rationale for not walking up the directory tree looking for `.babelrc` files is the following:
- A per-package `.babelrc` file seems sufficient
- It is much faster to just check the root of the package for a `.babelrc` file (the transform will run for every JS file so it needs to be fast)

Do you see a strong need for allowing `.babelrc` files at every level in the directory tree? We could make the change to search at all levels, or even make this an opt-in feature, but it would be ideal to avoid introducing the overhead if it won't cause problems (I realize third-party packages might be an issue...). Thoughts?

**Comment by austinkelleher** [comment]
I think that it would be ideal for the package to closely function like Babel CLI, but for most cases it wouldn't be necessary. I agree about having it as an opt-in feature.

The goal of my PR (https://github.com/lasso-js/lasso-babel-transform/pull/4) wasn't to completely replicate the functionality in the description though. I changed the code to use the `babel` property in package.json as a fallback technique if a `.babelrc` is not found. That is the way Babel CLI handles it.
