### ISSUE TITLE
Configuration?

### ISSUE THREAD

**Issue by basickarl** [lasso-js/lasso-babel-transform#6]
I'm trying to get lasso to transpile my es6 code.

https://github.com/lasso-js/lasso-babel-transform#usage

However I look at the https://github.com/lasso-js/lasso#complete-configuration I don't understand how I am to configure lasso to transpile my es6 code!

I tried the command lasso `src/page/public/public.browser.json --inject-into src/page/public/public.marko --development --config lasso.json` but got an error `Error: Cannot find module 'lasso-babel-transform'`, 

`lasso.json`:

```
{
    "plugins": [
        "lasso-sass"
    ],
    "outputDir": "/home/karl/dev/sketch/experiment/socketio/static",
    "urlPrefix": "/static",
    "fingerprintsEnabled": false,
    "require": {
        "transforms": [
            {
                "transform": "lasso-babel-transform",
                "config": {
                    "extensions": [
                        ".js",
                        ".es6"
                    ]
                }
            }
        ]
    },
    "bundlingEnabled": false
}
```

`/home/karl/dev/sketch/experiment/socketio/.babelrc`:

```
{
  "presets": [
    "es2015",
    "stage-3"
  ]
}
```

`/home/karl/dev/sketch/experiment/socketio/package.json`:

```
{
  "name": "experiment",
  "version": "0.0.1",
  "description": "",
  "dependencies": {},
  "devDependencies": {
    "babel-polyfill": "^6.13.0",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-stage-3": "^6.11.0",
    "babel-register": "^6.11.6",
    "lasso": "^2.5.8",
    "lasso-babel-transform": "^0.4.0",
    "lasso-marko": "^2.0.7",
    "lasso-sass": "^1.1.9"
  },
  "main": "app.js",
  "scripts": {},
  "author": "",
  "license": "ISC"
}
```

**Comment by patrick-steele-idem** [comment]
Your setup looks correct. The error suggests that the module is missing. Are you sure you ran `npm install`?

I went ahead and updated the sample [lasso-es6](https://github.com/lasso-js-samples/lasso-es6)  app to use the `lasso-babel-transform` and tested to make sure everything is working as expected and it is. If you are still stuck let us know.

**Comment by basickarl** [comment]
Cool thanks! I installed it globally and now it works. I ran lasso via the cli so I guess it checks the global node_modules directory.

Also a question on transpiling, I'm fairly new to the concept but this module (lasso-babel-transform) does it transpile at runtime or compiletime (or can it do both)? The example you linked to (with your update) shows that it transpiles at runtime (via middleware). How does one transpile it at compiletime?

**Comment by patrick-steele-idem** [comment]
Installing modules globally is generally a bad idea. It is best to install modules locally so the next person who tries to setup your project will get all dependencies (with the correct versions). The `lasso-babel-transform` module will be resolved relative to the Lasso configuration file so it should look in your project's `node_modules` directory.

Lasso can be invoked at build time or at runtime. It's designed to be fast enough to run at runtime since it makes use of a file system cache so there will only be a significant hit the first time. If you want to invoke lasso at build time then you can use the CLI. If you want to invoke lasso at runtime you can invoke the Lasso using the JavaScript API or you can use the Marko taglib (that internally calls the Lasso JavaScript API to asynchronously generate the JS/CSS bundles). When using the Marko taglib Lasso will be invoked when the page is loaded for the first time (and the result will be cached so that Lasso will impose no performance hit for the next request).

**Comment by basickarl** [comment]
I agree 100% with you. I did however.. forget to mention I'm using [NVM](https://github.com/creationix/nvm). In any case I forked your example and edited it.

To reproduce the error:

```
git clone git@github.com:basickarl/lasso-es6.git
cd lasso-es6
npm r -g lasso-babel-transform
npm install
npm run build-not-working
```

The error I receive when building is as follows:

```
karl@karl-ux303ln:~/dev/lasso-es6$ npm run build-not-working

> lasso-es6@0.0.0 build-not-working /home/karl/dev/lasso-es6
> ./build-not-working.sh

Config:
{
    "require": {
        "transforms": [
            {
                "transform": "lasso-babel-transform",
                "config": {
                    "extensions": [
                        ".js",
                        ".es6"
                    ]
                }
            }
        ]
    },
    "bundlingEnabled": false,
    "fingerprintsEnabled": false,
    "minify": false,
    "outputDir": "/home/karl/dev/lasso-es6/static",
    "urlPrefix": "%STATIC_PATH%"
}
module.js:442
    throw err;
    ^

Error: Cannot find module 'lasso-babel-transform'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.resolve (internal/module.js:27:19)
    at Transforms.transforms.forEach (/home/karl/.nvm/versions/node/v6.2.0/lib/node_modules/lasso-cli/node_modules/lasso-require/src/util/Transforms.js:95:53)
    at Array.forEach (native)
    at new Transforms (/home/karl/.nvm/versions/node/v6.2.0/lib/node_modules/lasso-cli/node_modules/lasso-require/src/util/Transforms.js:70:20)
    at buildPluginConfig (/home/karl/.nvm/versions/node/v6.2.0/lib/node_modules/lasso-cli/node_modules/lasso-require/src/build-plugin-config.js:109:46)
    at Object.plugin [as func] (/home/karl/.nvm/versions/node/v6.2.0/lib/node_modules/lasso-cli/node_modules/lasso-require/src/lasso-require-plugin.js:34:18)
    at Lasso.initPlugins (/home/karl/.nvm/versions/node/v6.2.0/lib/node_modules/lasso-cli/node_modules/lasso/lib/Lasso.js:513:20)
    at new Lasso (/home/karl/.nvm/versions/node/v6.2.0/lib/node_modules/lasso-cli/node_modules/lasso/lib/Lasso.js:485:10)
    at Object.create (/home/karl/.nvm/versions/node/v6.2.0/lib/node_modules/lasso-cli/node_modules/lasso/lib/index.js:53:20)

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/home/karl/.nvm/versions/node/v6.2.0/bin/node" "/home/karl/.nvm/versions/node/v6.2.0/bin/npm" "run" "build-not-working"
npm ERR! node v6.2.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! lasso-es6@0.0.0 build-not-working: `./build-not-working.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lasso-es6@0.0.0 build-not-working script './build-not-working.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lasso-es6 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./build-not-working.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lasso-es6
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lasso-es6
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/karl/dev/lasso-es6/npm-debug.log

```

I did get it to work however with the absolute path. When I run the following it works as it should (remember this is the absolute path on my computer, which is set to `/home/karl/dev/lasso-es6/node_modules/lasso-babel-transform`)

`npm run build-working`

**Comment by patrick-steele-idem** [comment]
The stack trace helped. The code is currently using `require.resolve` when it should be using [resolve-from](https://github.com/sindresorhus/resolve-from). Let me investigate a fix. Thanks for the details!

**Comment by patrick-steele-idem** [comment]
Fixed. See related issue on the [lasso-require](https://github.com/lasso-js/lasso-require) project: https://github.com/lasso-js/lasso-require/issues/37

Thanks again.

**Comment by basickarl** [comment]
No probs, happy to help! :)
